services:
  - type: web
    name: book-recommender
    env: python
    pythonVersion: "3.10"  # Force Python 3.10
    buildCommand: |
      pip install --upgrade pip
      pip install --upgrade setuptools
      pip install -r requirements.txt
    startCommand: "streamlit run app.py --server.port 8080"
    envVars:
      - key: PORT
        value: 8080
