services:
  - type: web
    name: book-recommender
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py"
    envVars:
      - key: PORT
        value: 8080
